version: '3.8'

services:
  novel-generator:
    build: .
    container_name: novel-generator
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
      - ./vectorstore:/app/vectorstore
      - ./config.json:/app/config.json
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped

  # 可选：添加向量数据库服务
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma-db
    volumes:
      - chroma-data:/chroma/data
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/data

volumes:
  chroma-data: